<x-app-layout>
    <x-slot name="header">
        <div class="flex min-w-0 items-center gap-3">
            <a href="{{ route('admin.assets.show', $asset) }}" class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-slate-900/80 text-slate-400 transition hover:border-indigo-400/40 hover:bg-indigo-500/10 hover:text-indigo-200 focus:outline-none focus:ring-2 focus:ring-indigo-500" aria-label="Voltar para o ativo"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="m15 19-7-7 7-7" /></svg></a>
            <div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-[0.18em] text-indigo-300">Inventário e governança</p><h2 class="truncate text-lg font-bold text-white sm:text-xl">Emitir termo de responsabilidade</h2></div>
        </div>
    </x-slot>

    <main class="mx-auto max-w-5xl py-2" x-data="{ type: @js(old('type', $asset->user_id ? 'return' : 'delivery')) }" aria-labelledby="term-create-title">
        <div class="grid gap-6 lg:grid-cols-12">
            <section class="space-y-6 lg:col-span-8">
                <x-validation-errors />
                <form method="POST" action="{{ route('admin.assets.terms.store', $asset) }}" class="overflow-hidden rounded-3xl border border-white/10 bg-slate-900/70 shadow-2xl shadow-slate-950/20 backdrop-blur-xl">
                    @csrf
                    <div class="border-b border-white/5 px-6 py-7 sm:px-8"><p class="text-[10px] font-bold uppercase tracking-[0.2em] text-indigo-300">Movimentação formal</p><h1 id="term-create-title" class="mt-2 text-xl font-black tracking-tight text-white sm:text-2xl">Registre a entrega ou devolução do ativo.</h1><p class="mt-2 text-sm leading-6 text-slate-400">O termo será assinado no dispositivo, armazenado de forma privada e disponibilizado em PDF após a confirmação.</p></div>

                    <div class="space-y-7 px-6 py-7 sm:px-8">
                        <fieldset><legend class="text-xs font-bold uppercase tracking-wider text-slate-400">Tipo de termo</legend><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="cursor-pointer"><input class="peer sr-only" type="radio" name="type" value="delivery" x-model="type"><span class="block rounded-2xl border border-white/10 bg-slate-950/45 p-4 transition peer-checked:border-indigo-400/50 peer-checked:bg-indigo-500/10"><span class="flex items-center gap-2 text-sm font-bold text-slate-200"><svg class="h-4 w-4 text-indigo-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 4v16m8-8H4" /></svg>Entrega</span><span class="mt-2 block text-xs leading-5 text-slate-500">Vincula o ativo ao responsável após a assinatura.</span></span></label><label class="cursor-pointer"><input class="peer sr-only" type="radio" name="type" value="return" x-model="type" {{ $asset->user_id ? '' : 'disabled' }}><span class="block rounded-2xl border border-white/10 bg-slate-950/45 p-4 transition peer-checked:border-amber-400/50 peer-checked:bg-amber-500/10 {{ $asset->user_id ? '' : 'cursor-not-allowed opacity-45' }}"><span class="flex items-center gap-2 text-sm font-bold text-slate-200"><svg class="h-4 w-4 text-amber-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M19 13h-8m0 0 3 3m-3-3 3-3M5 5v14a2 2 0 0 0 2 2h10" /></svg>Devolução</span><span class="mt-2 block text-xs leading-5 text-slate-500">Remove o responsável atual após a assinatura.</span></span></label></div></fieldset>

                        <div x-show="type === 'delivery'" x-cloak><label for="recipient_id" class="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">Responsável que receberá o ativo</label><select id="recipient_id" name="recipient_id" :required="type === 'delivery'" class="w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-500/20"><option value="">Selecione o responsável</option>@foreach($recipients as $recipient)<option value="{{ $recipient->id }}" @selected(old('recipient_id', $asset->user_id) == $recipient->id)>{{ $recipient->name }} · {{ $recipient->email }}</option>@endforeach</select></div>

                        <div x-show="type === 'return'" x-cloak class="rounded-2xl border border-amber-400/15 bg-amber-500/[0.06] p-4"><p class="text-xs font-bold text-amber-200">Responsável atual</p><p class="mt-1 text-sm font-semibold text-slate-200">{{ $asset->user?->name ?? 'Ativo sem responsável definido' }}</p><p class="mt-1 text-xs text-slate-500">Ao assinar o termo de devolução, este ativo volta para o estoque.</p></div>

                        <div class="rounded-2xl border border-cyan-400/15 bg-cyan-500/[0.05] p-4"><div class="flex gap-3"><svg class="mt-0.5 h-5 w-5 shrink-0 text-cyan-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" /></svg><div><h3 class="text-sm font-bold text-cyan-100">Evidência registrada</h3><p class="mt-1 text-xs leading-5 text-slate-400">A assinatura, data, IP, identificador do navegador e hash da imagem serão guardados junto ao termo. O PDF será gerado após a conclusão.</p></div></div></div>
                    </div>

                    <div class="flex flex-col-reverse gap-3 border-t border-white/5 bg-slate-950/25 px-6 py-5 sm:flex-row sm:items-center sm:justify-end sm:px-8"><a href="{{ route('admin.assets.show', $asset) }}" class="rounded-xl px-4 py-2.5 text-center text-sm font-semibold text-slate-400 transition hover:bg-white/5 hover:text-white">Cancelar</a><button type="submit" class="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-500 px-5 py-2.5 text-sm font-bold text-white transition hover:bg-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-300"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 4v16m8-8H4" /></svg>Gerar tela de assinatura</button></div>
                </form>
            </section>

            <aside class="space-y-5 lg:col-span-4"><section class="rounded-3xl border border-white/10 bg-slate-900/65 p-5 shadow-xl shadow-slate-950/15"><p class="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Ativo selecionado</p><h2 class="mt-2 text-lg font-bold text-white">{{ $asset->name }}</h2><dl class="mt-5 space-y-3 text-xs"><div class="flex justify-between gap-3"><dt class="text-slate-500">Patrimônio</dt><dd class="font-mono font-semibold text-slate-300">{{ $asset->tag }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Serial</dt><dd class="max-w-[60%] truncate font-mono font-semibold text-slate-300">{{ $asset->serial_number ?: 'Não informado' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Responsável</dt><dd class="max-w-[60%] truncate text-right font-semibold text-slate-300">{{ $asset->user?->name ?? 'Em estoque' }}</dd></div></dl></section><section class="rounded-3xl border border-indigo-400/15 bg-gradient-to-br from-indigo-500/10 to-slate-900/80 p-5"><h2 class="text-sm font-bold text-white">Fluxo em três etapas</h2><ol class="mt-4 space-y-3 text-xs leading-5 text-slate-400"><li class="flex gap-2"><span class="font-bold text-indigo-300">1.</span>Emita o termo para a movimentação.</li><li class="flex gap-2"><span class="font-bold text-indigo-300">2.</span>Entregue o dispositivo ao responsável para assinatura.</li><li class="flex gap-2"><span class="font-bold text-indigo-300">3.</span>Baixe o PDF e consulte o histórico do ativo.</li></ol></section></aside>
        </div>
    </main>
</x-app-layout>
